[package]
name = "argent-template"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.0"
license = "ISC"
publish = false
default-run = "counter"

[dependencies]
argent = { path = "../argent" }
argent-runtime = { path = "../argent/crates/argent-runtime" }
blake2b_simd = "1.0.4"
kaspa-consensus-core = { git = "https://github.com/kaspanet/rusty-kaspa", rev = "a41a333b08848f41bf737b72592e463a6011b8ac" }
secp256k1 = { version = "0.29.0", features = ["global-context"] }
